DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE Curso (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT UNIQUE NOT NULL,
  descricao  TEXT NOT NULL
);

CREATE TABLE Turma (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  curso_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  FOREIGN KEY (curso_id) REFERENCES Curso (id)
);

CREATE TABLE Matricula (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  turma_id INTEGER NOT NULL,
  nome_aluno TEXT NOT NULL,
  FOREIGN KEY (turma_id) REFERENCES Turma (id)
);
